name: safiroute
description: SafiRoute native Sales waybill app for Safisana Ghana.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.0
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2
  geolocator: ^13.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  shared_preferences: ^2.3.2
  signature: ^5.5.0
  sqflite: ^2.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/safiroute-logo.png
    - assets/safiroute-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/safiroute-icon.png
  adaptive_icon_background: "#F4EFE2"
  adaptive_icon_foreground: assets/safiroute-icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F4EFE2"
  image: assets/safiroute-icon.png
  android_12:
    color: "#F4EFE2"
    image: assets/safiroute-icon.png
