# Generated by Django 5.1.7 on 2026-09-14 14:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=40, unique=True)),
                ('delivery_address', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('ghana_post_gps', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('unit_of_measure', models.CharField(default='bag', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=24, unique=True)),
                ('transport_company', models.CharField(default='Safisana Ghana', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Officer'), ('supervisor', 'Sales Supervisor'), ('warehouse', 'Warehouse Officer'), ('driver', 'Driver / Delivery Officer'), ('finance', 'Finance / Audit Viewer')], default='sales', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(default='Ashaiman Plant', max_length=120)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('verification_token', models.CharField(editable=False, max_length=48, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('loaded', 'Loaded'), ('dispatched', 'Dispatched'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially delivered'), ('delivery_failed', 'Delivery failed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='synced', max_length=16)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('sales_order_ref', models.CharField(blank=True, max_length=64)),
                ('invoice_ref', models.CharField(blank=True, max_length=64)),
                ('po_ref', models.CharField(blank=True, max_length=64)),
                ('branch', models.CharField(default='Ashaiman Plant', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=32)),
                ('dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dispatch_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dispatch_gps_accuracy', models.FloatField(blank=True, null=True)),
                ('delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_device_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('delivery_gps_accuracy', models.FloatField(blank=True, null=True)),
                ('gps_unavailable_reason', models.CharField(blank=True, max_length=240)),
                ('customer_rep_name', models.CharField(blank=True, max_length=160)),
                ('customer_rep_role', models.CharField(blank=True, max_length=80)),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('driver_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('delivery_notes', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='waybills/')),
                ('pdf_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_waybills', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_waybills', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='waybills.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_waybills', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waybills.vehicle')),
                ('warehouse_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loaded_waybills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='waybills.waybill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=40)),
                ('unit_of_measure', models.CharField(max_length=24)),
                ('ordered_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loaded_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivered_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waybills.product')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='waybills.waybill')),
            ],
        ),
        migrations.CreateModel(
            name='WaybillPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='waybills.waybill')),
            ],
        ),
    ]
