# Generated by Django 5.2.8 on 2026-09-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='authorised_by_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='waybill',
            name='authorised_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='waybill',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='waybill',
            name='deliver_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='waybill',
            name='delivery_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='waybill',
            name='delivery_contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='waybill',
            name='dispatched_by_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='waybill',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waybillitem',
            name='ordered_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='waybillitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waybills.product'),
        ),
        migrations.AlterField(
            model_name='waybillitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='waybillitem',
            name='sku',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='waybillitem',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
